# TODO: Completez ce Dockerfile multi-stage
# Stage 1: Builder - python:3.11-slim, installer deps
# Stage 2: Final - python:3.11-slim, copier deps+code, USER 1001, HEALTHCHECK, port 8000
FROM python:3.11-slim AS builder
# TODO

FROM python:3.11-slim
# TODO
